MACHINE_HISTORY = {
    "CRATES AREA": [
        "Aligned the drive sprocket and corrected conveyor tracking.",
        "Secured lifter roller guide by installing missing bolt.",
        "Reconnected multiple cut or damaged conveyor sections and restored conveyor continuity.",
        "Rectified conveyor line faults, including derailed and jammed sections.",
        "Checked and corrected stacker and destacker operational faults.",
        "Repaired and realigned crates lifter arm assemblies.",
        "Removed worn bearings and broken bolts; installed new bearings and hardware.",
        "Removed drive motor and sprocket, replenished shaft, and reinstalled complete drive assembly.",
        "Repaired damaged overhead conveyors, including link replacement and structural welding.",
        "Repaired damaged inclined conveyor and restored chain tension.",
        "Replaced damaged or broken sensors (crates detection, destacker, safety, infeed).",
        "Replaced damaged drive sprocket and overhead conveyor sprocket.",
        "Replaced crates lifter arm base block bearings and spindle shaft swing arm bearings.",
        "Replaced damaged plastic guide on S/S infeed conveyor and corrected loose links.",
        "Replaced defective cables, photo sensors, and wiring connections.",
        "Reset conveyor system faults, VFD alarms, and motor protection trips.",
        "Cleaned motor terminals and restored electrical continuity.",
        "Repaired broken rods and welded damaged components as required.",
        "Removed broken conveyor links and reconnected overhead crates divider conveyor; reset drive motor fault.",
        "Removed damaged drive shaft and sprocket for machining and rebuild.",
        "Installed new drive motor and restored system operation.",
        "Secured mounting of destacker crates presence sensor and corrected conveyor derailment.",
        "Tightened chain tensioner; noted requirement for sprocket replacement.",
        "Replaced busted fuse and restored panel breaker operation.",
        "Repaired and adjusted crates conveyor system to eliminate repeated stoppages.",
        "Replaced damaged overhead crates conveyor sections and restored full movement.",
        "Performed general welding, fabrication, and mechanical corrections across conveyor assemblies.",
        "Logged condition: one side running manually; replacement sprocket machining required.",
        "Noted damaged arm bearings for day shift follow‑up."
    ],
    "M1": [
        "Adjusted capper mechanisms including cap chute, cap dispenser, cap sorter, and overall capper alignment.",
        "Fine-tuned torque settings and air regulators for stable capping performance.",
        "Aligned capping heads and cap applicator assemblies to correct misalignment and improve cap placement accuracy.",
        "Checked and adjusted filler cylinder rod and product regulating valve to stabilize filling operation.",
        "Rectified capper #1 and #4 issues, including height adjustment of cap dispenser and replacement of capper finger pin.",
        "Repaired and adjusted cap holder assembly; noted finger cam replacement requirement.",
        "Replaced broken filler piston, broken nozzle pin, and defective sensors/cables.",
        "Replaced capper spindle using available spare and fine-tuned jaw air pressure.",
        "Replaced defective torque limiter and restored proper torque control.",
        "Replaced capper piston assembly and corrected timing after detachment from the mechanism.",
        "Installed new air regulator to stabilize jaw air pressure.",
        "Lubricated capper assembly and performed routine mechanical adjustments.",
        "Fabricated and installed capper bottle guide to correct bottle flow issues.",
        "Repaired overhead conveyor sprocket and reconnected broken overhead conveyor sections.",
        "Removed broken conveyor links, replaced damaged links, and restored conveyor operation.",
        "Removed sliding plate bracket, extracted broken bolt, replaced hardware, and reinstalled assembly.",
        "Reset VLT/VFD drive faults, motor faults, stacker faults, and circuit breaker trips.",
        "Troubleshot auto-mode failure; found solenoid valves contaminated with water, cleaned and replaced corroded coils.",
        "Troubleshot carriage plate not opening and resolved mechanical obstruction.",
        "Troubleshot automatic operation failure; corrected loose selector switch connection.",
        "Released air lock and restored pneumatic operation.",
        "Repaired stacker system issues and reset crates stacker system fault.",
        "Welded cap applicator lock to eliminate excessive movement and prevent misalignment.",
        "Repaired damaged crates conveyor and restored overhead conveyor alignment.",
        "Rebalanced crates lifter and cleared system fault.",
        "Updated machine message display due to corrupted characters."
    ],
    "M13": [
        "Adjusted chain pusher alignment, carton alignment, and machine homing position.",
        "Adjusted chain packer alignment and corrected timing issues.",
        "Adjusted and aligned sensors for proper detection.",
        "Fine-tuned printer settings and cleaned inkjet printhead.",
        "Cleaned vacuum generator on both sides to improve suction performance.",
        "Cleaned glue nozzle and secured solenoid valve socket.",
        "Replaced damaged air hose and restored pneumatic connections.",
        "Replaced motor #3 and configured motor parameters; machine monitoring confirmed OK.",
        "Retimed carton chain pusher and carton forming chain.",
        "Corrected pusher sensor alignment to eliminate false activation.",
        "Released air lock in pneumatic system and restored operation.",
        "Cleaned and serviced inkjet system for print quality improvement.",
        "Adjusted pallet conveyor speed for stable pallet movement.",
        "Repaired water leakage at union coupling.",
        "Performed full machine timing correction; reset all timing points to zero and manually aligned all mechanisms.",
        "Performed scale calibration and dynamic calibration.",
        "Released air lock of pump and restored product flow.",
        "Removed pallet manually to clear jam and reset system.",
        "Repaired Lanfranchi bottle guide and restored bottle flow.",
        "Repaired bottle gate; replaced detached bolt and hose fitting.",
        "Replaced broken bottom plate pin and cleaned bottom plate assembly.",
        "Replaced broken carton bar chain pin and retimed carton forming chain.",
        "Replaced damaged bottle stopper cylinder and restored operation.",
        "Replaced damaged cylinder hose fitting.",
        "Replaced positive chuck assembly.",
        "Replaced printer with spare due to persistent poor printing.",
        "Replaced transport guide in curve area to eliminate bottle jamming.",
        "Reset palletizer fault, barrier fault, VFD fault, and WAGO defect.",
        "Troubleshot product pusher malfunction and turned over remaining work to night shift.",
        "Noted absence of operator during troubleshooting events."
    ],
    "M14": [
        "Adjusted bottle screw timing, bottle guides, intermediate infeed screw, and overall bottle handling alignment.",
        "Corrected timing of bottle screw, starwheel, separation bar, and tray feeding chain.",
        "Adjusted Promec height, starwheel-to-filler alignment, and bottle holder alignment.",
        "Adjusted opening of air-conveyor bottle-neck guides and corrected Lanfranchi bottle guide alignment.",
        "Set machine to zero position multiple times after timing drift or mechanical obstruction.",
        "Performed homing adjustments after clearing jams or mechanical resets.",
        "Aligned capper head and adjusted air pressure for capping.",
        "Repaired capper #1, #4, #6, and #13 assemblies.",
        "Replaced capper head fingers and micro-switches; interchanged capper chucks as needed.",
        "Fine-tuned air pressure for cap holding and tightening.",
        "Repaired cap holder assembly and replaced broken springs, holders, and pivot components.",
        "Adjusted filling sensor sensitivity and corrected sensor alignment across multiple stations.",
        "Reset sequence faults, conveyor system faults, head safety faults, temperature faults, and VLT/VFD alarms.",
        "Troubleshot and replaced defective solid-state relays, micro switches, and malfunctioning sensors.",
        "Repaired head safety sensor and corrected air-valve activation signal.",
        "Rewired stacker safety relay reset circuit after electrical fault.",
        "Checked and corrected encoder belt alignment; replaced encoder bearing due to water ingress.",
        "Reset Sipac downline electrical circuits after power fluctuation.",
        "Fixed multiple air leakages, replaced damaged hoses, fittings, and leaking cylinders.",
        "Repaired micro-valve assemblies and replaced broken bolts and fittings.",
        "Replaced air control regulator for carton folder cylinder.",
        "Released air locks in pneumatic lines and restored normal operation.",
        "Repaired bottle holders, replaced broken springs, and corrected bottle holder alignment.",
        "Repaired bottle gate, bottle screw coupling, and replaced damaged pins.",
        "Cleared clogged bottles at funnel and restored conveyor safety sensor activation.",
        "Repaired Promec drier bottle holder and corrected outfeed starwheel alignment.",
        "Released stuck conveyors, reconnected conveyor links, and restored bottle flow.",
        "Repaired infeed bottle gate and corrected pusher chain issues.",
        "Cleaned and adjusted glue nozzle; rectified glue application issues.",
        "Cleaned printhead, adjusted printing parameters, and aligned inkjet system.",
        "Replaced malfunctioning printer with standby unit; replaced laminar pre-filters.",
        "Adjusted printer sensor sensitivity and corrected message display issues.",
        "Lubricated filler carousel and reduced machine speed for stability.",
        "Replaced broken bottom plate springs and damaged holders.",
        "Corrected rinser temperature fault and adjusted return valve spring.",
        "Replaced damaged steam gauge with new pressure gauge.",
        "Replaced busted multiflow units, coils, and cables; cleaned sockets and calibrated stations.",
        "Manually cycled valves and restored washing mode after malfunction.",
        "Welded broken crates stopper cylinder holder and repaired structural components.",
        "Repaired middle bottle screw and secured loose mounting hardware.",
        "Replaced damaged transport plastic guide and bottle gripper components.",
        "Performed zeroing of scales and dynamic calibration.",
        "Reset machine position after timing corrections and mechanical resets.",
        "Reset multiple system alarms including servo driver, orientator conveyor, and safety faults."
    ],
    "M16": [
        "Adjusted bottle screw timing and infeed screw timing to correct bottle flow.",
        "Adjusted capper belt tension and fine-tuned torque pressure for stable capping.",
        "Retimed bottle screw guide and corrected cap chute guide alignment.",
        "Adjusted plastic roller presser and restored proper pressure settings.",
        "Checked and adjusted air pressure for capping operation.",
        "Rectified issues on capper #1 and #2, including alignment and torque correction.",
        "Replaced broken bearing of capper belt roller.",
        "Repaired leaking nozzle #17 and verified sealing performance.",
        "Aligned pallet wrapper safety barrier sensor and restored safety circuit.",
        "Rectified valve faults, glue tank faults, and CIP system faults.",
        "Reset VFD faults and general machine faults after troubleshooting.",
        "Monitored CIP system operation until completion and restarted CIP cycle when required.",
        "Cleaned glue nozzles and corrected glue application issues.",
        "Replaced damaged plastic cutting drive and restored glue nozzle performance.",
        "Cooled down hot-flush line and corrected cooling step issues.",
        "Performed temperature cooldown to transfer cooling to drain system.",
        "Repaired bottle gate stopper and restored proper actuation.",
        "Removed rolled plastic from outfeed mesh conveyor roller and reinstalled cleaned roller.",
        "Repaired stuck film roller and restored smooth film movement.",
        "Replaced broken film rise belt and repaired film rise table conveyor during CIP.",
        "Replaced broken packer outfeed plastic conveyor and reinstalled assembly.",
        "Mounted missing belt on roller, cleaned glue nozzle, adjusted guides, and performed homing.",
        "Repaired passage cylinder guide and restored alignment.",
        "Fixed air leakage issues and restored pneumatic pressure stability.",
        "Checked and rectified glue issues and valve faults.",
        "Checked cause of hot-flush issue and corrected cooling sequence.",
        "Cleaned glue nozzles and performed routine nozzle maintenance.",
        "Reset machine faults after mechanical or electrical corrections."
    ],
    "M15": [
        "Adjusted bottle gate #1 and #2, bottle infeed screw, bottle separator belt, and bottle guides.",
        "Adjusted orientator exit conveyor belt and mat conveyor tensioner.",
        "Adjusted cylinder stroke and installed spacer for bottle gate alignment.",
        "Aligned bottle holders to starwheel and corrected bottle funnel swing angle plate.",
        "Zeroed machine position after timing drift or mechanical resets.",
        "Performed full dynamic scale calibration.",
        "Adjusted air pressure for capping and fine-tuned torque and holding air regulators.",
        "Repaired capper #2 and replaced cap holder fingers.",
        "Repaired cap holder assembly and corrected misalignment.",
        "Repaired bottle elevator safety actuator and safety sensor; released stuck elevator and reset faults.",
        "Repaired bottle stopper and replaced damaged stopper cylinder shaft bolt.",
        "Replaced broken bottle holder bushings, plastic grippers, and springs.",
        "Installed sensor mirror to activate table conveyor flag sensor.",
        "Adjusted printer sensor sensitivity and corrected message parameters.",
        "Checked and rectified safety sensor faults, stacker limit sensor faults, and missing sensor feedback signals.",
        "Reset servo drive faults, VLT faults, orientator servo faults, door safety faults, and general machine faults.",
        "Rewired stacker #1 safety relay reset circuit after electrical malfunction.",
        "Replaced defective sensor cables for drain pad and other detection points.",
        "Reset Sipac downline electrical circuits after power fluctuation.",
        "Repaired outfeed conveyor of stacker #1 and restored belt tracking.",
        "Repaired broken crates feeding conveyor and reconnected broken crates conveyor.",
        "Repaired belt damage and applied adhesive reinforcement.",
        "Replaced damaged belts in orientator and outfeed areas using available spares.",
        "Removed rolled plastic from outfeed mesh conveyor roller and restored operation.",
        "Fixed multiple air leakages and replaced damaged hoses, fittings, and leaking cylinders.",
        "Lubricated cylinders, stopper cylinders, and solenoid valve air lines.",
        "Filled lubrication oil for packer bottle stopper solenoid valve.",
        "Repaired cylinder #3 gate stopper and replaced defective cylinders with new units.",
        "Checked multiflow units, replaced grounded cables, busted card fuses, and defective coils.",
        "Replaced multiflow coil at station #35 and cleaned socket plugs for stations #6 and #20.",
        "Checked valve conditions for product leakage; no issues found.",
        "Adjusted ink and printer parameters; cleaned and aligned print jet.",
        "Replaced malfunctioning printer with standby unit and installed printer from M7 when required.",
        "Printer marked for replacement due to recurring issues.",
        "Cleaned glue nozzles and corrected glue application issues.",
        "Adjusted glue nozzle position and secured solenoid valve socket.",
        "Welded broken crates stopper cylinder holder.",
        "Repaired defective funnel and corrected bottle funnel clogging during CIP.",
        "Added make-up solution to correct viscosity.",
        "Insulated bottle orientator outfeed belt and tightened cylinder stopper bolts.",
        "Fixed conveyor issues and restored smooth movement.",
        "Fixed air blower for bottle printing.",
        "Repaired air leakage for capper #5.",
        "Replaced laminar flow filters.",
        "Replaced TES+ card fuse for stations #19 & #20 and restored multiflow circuit.",
        "Reset full line crates sensor and restored detection accuracy."
    ],
    "M17": [
        "Aligned bottle exit starwheel to guide and corrected bottle entry alignment at rinser holders #10 and #25.",
        "Adjusted bottle rejector exit conveyor guide to reduce bottle downing; machine speed temporarily reduced to 180 ppm.",
        "Adjusted bottle rejector safety alignment and corrected bottle stopper looseness.",
        "Set machine to zero position and synchronized timing after mechanical resets.",
        "Aligned and adjusted bottle filling sensor and corrected sensitivity settings.",
        "Repaired capper #5 and #6 assemblies and replaced locator plate for capper #1 using available spare.",
        "Removed clogged caps from cap conveyor and restored cap flow.",
        "Repaired bottle holder #10 and replaced broken roller shaft and bottle-neck locator using old spare.",
        "Replaced worn-out gasket and restored sealing performance.",
        "Adjusted sensor sensitivity and rectified faulty sensor signals.",
        "Repaired sensor connections and replaced defective sensor cables for valves and detection points.",
        "Fixed door safety switch connection and restored safety circuit.",
        "Disabled station #14 for post-production inspection.",
        "Reset machine faults after troubleshooting and restored missing sensor feedback signals.",
        "Repaired conveyor sections and corrected alignment issues.",
        "Released stuck carton pusher, replaced broken chain lock, and straightened bent pusher plate.",
        "Removed rolled plastic from outfeed mesh conveyor roller and reinstalled cleaned roller.",
        "Repaired bottle entry alignment at rinser and corrected bottle flow issues.",
        "Eliminated air hose leakages and repaired leaking air lines.",
        "Repaired air leakage in multiple stations and restored pneumatic pressure stability.",
        "Replaced damaged air hose and fittings for station #7.",
        "Opened clogged multiflow and removed rubber obstruction.",
        "Repaired detached nozzle tip of multiflow and restored flow accuracy.",
        "Replaced filler multiflow coil using repaired spare and calibrated system.",
        "Replaced cable and multiflow assembly, followed by calibration.",
        "Rectified valve 19V24 and restored proper operation.",
        "Adjusted print parameters and cleaned/aligned printhead to correct bad printing.",
        "Performed nozzle cleaning due to ink misalignment with gutter.",
        "Adjusted printer settings after parameter replacement.",
        "Replaced broken angle support and shaft.",
        "Replaced broken lock for bottle swing stopper.",
        "Performed welding repairs on structural components as required.",
        "Repaired glue system issues and corrected glue application.",
        "Repaired air leakage and restored pneumatic stability.",
        "Repaired and aligned cap holder and allocator.",
        "Replaced worn or damaged components including bottle locator, springs, and gaskets.",
        "Set machine to zero position and synchronized system after major adjustments."
    ],
    "M18": [
        "Adjusted timing of infeed bottle screw and bottle screw guide; corrected synchronization issues.",
        "Adjusted separation bar, bottle guide, locator alignment, and infeed screw alignment.",
        "Zeroed machine position after timing drift and restored synchronization.",
        "Corrected bottle holder alignment and replaced fork for juice line; secured locking mechanism.",
        "Aligned cap dispenser and corrected capper lock issues.",
        "Identified multiple damaged bottle-neck locators requiring replacement; several stations temporarily disabled due to no spare availability.",
        "Repaired bottle stopper and corrected loose capping issues.",
        "Replaced broken bottle holder and broken lock pin using fabricated spare.",
        "Repaired damaged angle support at station #14 and replaced neck locators for capper heads #8, #10, and #11.",
        "Replaced broken capper bottle stopper fork.",
        "Activated soda level probe signal.",
        "Adjusted sensor sensitivity and rectified faulty sensor signals.",
        "Repaired sensor connections and replaced defective sensor cables.",
        "Disabled stations with defective locators pending spare availability.",
        "Reset CIP plant and corrected tank emptying valve settings.",
        "Set up Imaje printer due to solvent shortage for Leibinger unit.",
        "Checked and aligned carton conveyor guide.",
        "Repaired plastic roller and replaced damaged plastic cutter.",
        "Released stuck carton pusher, replaced broken chain lock, and straightened bent pusher plate.",
        "Repaired bottle entry alignment at rinser and corrected bottle flow issues.",
        "Repaired multiple air leakages and replaced damaged air hoses and fittings.",
        "Rectified air leakage in pallet wrapper air supply.",
        "Replaced leaking air hose and secured connections with cable ties.",
        "Found broken multiflow pin; scheduled replacement after production.",
        "Repaired detached multiflow nozzle tip and restored flow accuracy.",
        "Replaced defective multiflow and cable; calibrated system.",
        "Replaced filler multiflow coil using repaired spare.",
        "Cleaned and drained glue nozzle hose; removed blockages.",
        "Replaced acid pump exhaust pipe union gasket.",
        "Adjusted printer parameters and cleaned inkjet head.",
        "Performed ink-line cleaning and restarted inkjet system.",
        "Replaced printer unit with Imaje due to Leibinger viscosity motor fault; later reinstalled Leibinger unit and tested.",
        "Set up black Imaje printer due to solvent shortage.",
        "Repaired damaged angle support and replaced broken shaft.",
        "Repaired bottle stopper and reinforced locking components.",
        "Changed gasket and replaced worn-out gaskets where required.",
        "Removed clogged caps from cap conveyor.",
        "Repaired damaged plastic cutter and restored cutting performance.",
        "Performed retiming of infeed bottle screw and corrected capper lock.",
        "Noted need to replace bottle-neck locators and allocator; no spare available.",
        "Noted need to top-up make-up solution; stock unavailable."
    ]
}
